# Generated by Django 4.0.6 on 2023-05-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(help_text='nombres', max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(help_text='apellidos', max_length=100, verbose_name='apellidos')),
                ('birthday', models.DateField(blank=True, help_text='fecha de nacimiento', null=True, verbose_name='fecha de nacimiento')),
                ('identification', models.CharField(help_text='numero de identificacion', max_length=100, verbose_name='numero de identificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(help_text='nombres', max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(help_text='apellidos', max_length=100, verbose_name='apellidos')),
                ('birthday', models.DateField(blank=True, help_text='fecha de nacimiento', null=True, verbose_name='fecha de nacimiento')),
                ('identification', models.CharField(help_text='numero de identificacion', max_length=100, verbose_name='numero de identificacion')),
                ('expedition_place', models.CharField(help_text='lugar de expedicion', max_length=100, verbose_name='lugar de expedicion')),
                ('email', models.CharField(help_text='correo electronico', max_length=100, verbose_name='correo electronico')),
                ('address', models.CharField(help_text='direccion', max_length=100, verbose_name='direccion')),
                ('phone_number', models.CharField(help_text='numero de telefono', max_length=100, verbose_name='numero de telefono')),
                ('transfer', models.CharField(blank=True, help_text='transferencia', max_length=100, verbose_name='transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='kinship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre del parentesco', max_length=100, verbose_name='nombre del parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre', max_length=100, verbose_name='nombre')),
                ('description', models.CharField(help_text='descripcion', max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('expedition_date', models.DateField(blank=True, help_text='fecha de expedicion', null=True, verbose_name='fecha de expedicion')),
                ('Asesor', models.ForeignKey(help_text='Asesor', on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='Asesor')),
                ('Beneficiary', models.ManyToManyField(help_text='beneficiario', to='contracts.beneficiary', verbose_name='beneficiario')),
                ('client', models.ForeignKey(help_text='cliente', on_delete=django.db.models.deletion.CASCADE, to='contracts.client', verbose_name='cliente')),
                ('plan', models.ForeignKey(help_text='plan', on_delete=django.db.models.deletion.CASCADE, to='contracts.plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='kinship',
            field=models.ForeignKey(help_text='parentesco', on_delete=django.db.models.deletion.CASCADE, to='contracts.kinship', verbose_name='parentesco'),
        ),
    ]
