# Generated by Django 4.1.7 on 2023-03-16 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipe_identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='phone number', max_length=20, verbose_name='phone number')),
                ('address', models.CharField(blank=True, help_text='address', max_length=100, verbose_name='address')),
                ('image', models.ImageField(blank=True, help_text='image', upload_to='profile_images', verbose_name='image')),
                ('info_extra', models.TextField(blank=True, help_text='info extra', verbose_name='info extra')),
                ('identification', models.CharField(blank=True, help_text='identification', max_length=20, verbose_name='identification')),
                ('bithday', models.DateField(blank=True, help_text='bithday', null=True, verbose_name='bithday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='authentication.role')),
                ('tipe_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='authentication.tipe_identification')),
                ('user', models.OneToOneField(blank=True, help_text='choose user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
