# Generated by Django 4.1.7 on 2023-03-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='rol_name',
        ),
    ]
