# Generated by Django 4.0.6 on 2023-05-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_name_role_rol_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipe_identification',
            new_name='Identification_type',
        ),
        migrations.RenameField(
            model_name='identification_type',
            old_name='tipe',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tipe_identification',
            new_name='id_type',
        ),
    ]
