# Generated by Django 4.0.6 on 2023-05-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_tipe_identification_identification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bithday',
            new_name='birthday',
        ),
    ]
