# Generated by Django 4.0.6 on 2023-05-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_id_type_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='birthday', null=True, verbose_name='birthday'),
        ),
    ]
